/// Calculate XP awarded for killing a monster.
/// Formula: 1 + level² + guard_bonus
/// guard_bonus: 2 XP per guard point above the baseline 10.
pub fn monster_xp(level: u8, guard: u8) -> u32 {
    let base = 1u32 + (level as u32) * (level as u32);
    let guard_bonus = u32::from(guard.saturating_sub(10)) * 2;
    base + guard_bonus
}

/// Party XP bonus per eligible member beyond the first. A full 5-member
/// party pools exactly double the solo award.
pub const PARTY_XP_BONUS_PER_EXTRA_PERCENT: u64 = 25;

/// XZ distance from the dying monster within which a living, same-floor
/// party member shares the kill XP. Sized to cover one hunting ground
/// (ambient spawns land within 60m of each member) without letting a
/// party leech across the map.
pub const PARTY_XP_SHARE_RADIUS: f32 = 150.0;

/// Equal per-member share of a monster's XP among `eligible_members` party
/// members. The killing blow gets no special cut — it only triggers the
/// split. The pool gains the party bonus, the split is floored, and each
/// member is guaranteed 1 XP (0 stays 0). Padding a party with idle members
/// cannot beat soloing, which holds only while the bonus stays at or below
/// 100% per extra member — see `party_share_never_beats_soloing`.
pub fn party_xp_share(base_xp: u32, eligible_members: u32) -> u32 {
    let n = eligible_members.max(1);
    if n == 1 {
        return base_xp;
    }
    let percent = 100 + PARTY_XP_BONUS_PER_EXTRA_PERCENT * u64::from(n - 1);
    let total = (u64::from(base_xp) * percent / 100) as u32;
    (total / n).max(1.min(base_xp))
}

/// Cumulative XP to reach levels 2..=50, paced by play time
/// (doc/LEVEL_CURVE.md, generated by scripts/level_curve.py).
const LEVEL_XP: [u64; 49] = [
    17, 76, 226, 586, 1256, 2356, 4056, 6556, 9956, 17156, 29156, 48156, 74156, 110156, 158156,
    219156, 296156, 391156, 511156, 651156, 811156, 1001156, 1231156, 1491156, 1791156, 2131156,
    2521156, 2961156, 3451156, 3991156, 4581156, 5221156, 5911156, 6661156, 7471156, 8341156,
    9271156, 10271156, 11371156, 12571156, 13771156, 15071156, 16471156, 17971156, 19571156,
    21271156, 23071156, 24971156, 26971156,
];

/// Minimum cumulative XP required to reach the given level. Table-driven to
/// 50; past it every level doubles, saturating at u64::MAX (~level 90).
pub fn xp_for_level(level: u32) -> u64 {
    if level <= 1 {
        return 0;
    }
    let top = LEVEL_XP.len() as u32 + 1;
    if level <= top {
        return LEVEL_XP[(level - 2) as usize];
    }
    let shift = level - top;
    if shift >= 64 {
        return u64::MAX;
    }
    LEVEL_XP[LEVEL_XP.len() - 1].saturating_mul(1u64 << shift)
}

/// Determine current level from cumulative XP. No upper bound.
pub fn level_from_xp(xp: u64) -> u32 {
    let mut level = LEVEL_XP.partition_point(|&threshold| xp >= threshold) as u32 + 1;
    while level < u32::MAX {
        let next = xp_for_level(level + 1);
        if xp < next || next == u64::MAX {
            break;
        }
        level += 1;
    }
    level
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DeathPenaltyResult {
    pub old_level: u32,
    pub new_level: u32,
    pub old_xp: u64,
    pub new_xp: u64,
    pub xp_penalty: u64,
    pub leveled_down: bool,
}

/// Apply death penalty to cumulative XP.
/// - XP loss: 15% of current level band (minimum 1)
/// - If below current level start XP, lose exactly 1 level (unless level 1)
/// - On level down, guarantee at least 30% progress in lower level band
pub fn apply_death_penalty(old_xp: u64) -> DeathPenaltyResult {
    let old_level = level_from_xp(old_xp);
    let level_start_xp = xp_for_level(old_level);
    let next_level_xp = xp_for_level(old_level.saturating_add(1));
    let level_band = next_level_xp.saturating_sub(level_start_xp);
    let xp_penalty = (level_band.saturating_mul(15) / 100).max(1);

    let mut new_xp = old_xp.saturating_sub(xp_penalty);
    let mut new_level = old_level;
    let mut leveled_down = false;

    if old_level > 1 && new_xp < level_start_xp {
        leveled_down = true;
        new_level = old_level - 1;

        let lower_start_xp = xp_for_level(new_level);
        let lower_next_xp = xp_for_level(new_level.saturating_add(1));
        let lower_band = lower_next_xp.saturating_sub(lower_start_xp);
        let recovery_floor = lower_start_xp.saturating_add(lower_band.saturating_mul(30) / 100);
        new_xp = new_xp.max(recovery_floor);
    }

    DeathPenaltyResult {
        old_level,
        new_level,
        old_xp,
        new_xp,
        xp_penalty,
        leveled_down,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn monster_xp_no_guard_bonus() {
        // level 3, guard 10: 1 + 9 + 0 = 10
        assert_eq!(monster_xp(3, 10), 10);
    }

    #[test]
    fn monster_xp_below_baseline_guard_has_no_penalty() {
        assert_eq!(monster_xp(3, 8), 10);
    }

    #[test]
    fn monster_xp_guard_above_baseline() {
        // level 5, guard 12: 1 + 25 + 4 = 30
        assert_eq!(monster_xp(5, 12), 30);
    }

    #[test]
    fn monster_xp_high_guard() {
        // level 8, guard 13: 1 + 64 + 6 = 71
        assert_eq!(monster_xp(8, 13), 71);
    }

    #[test]
    fn xp_for_level_thresholds() {
        assert_eq!(xp_for_level(1), 0);
        assert_eq!(xp_for_level(2), 17);
        assert_eq!(xp_for_level(3), 76);
        assert_eq!(xp_for_level(10), 9956);
        assert_eq!(xp_for_level(50), 26_971_156);
        assert_eq!(xp_for_level(51), 53_942_312);
        assert_eq!(xp_for_level(52), 107_884_624);
    }

    #[test]
    fn xp_for_level_is_strictly_increasing() {
        for level in 2..=89 {
            assert!(
                xp_for_level(level) > xp_for_level(level - 1),
                "level {level}"
            );
        }
    }

    #[test]
    fn level_from_xp_basic() {
        assert_eq!(level_from_xp(0), 1);
        assert_eq!(level_from_xp(16), 1);
        assert_eq!(level_from_xp(17), 2);
        assert_eq!(level_from_xp(75), 2);
        assert_eq!(level_from_xp(76), 3);
        assert_eq!(level_from_xp(9956), 10);
        assert_eq!(level_from_xp(26_971_156), 50);
        assert_eq!(level_from_xp(53_942_311), 50);
        assert_eq!(level_from_xp(53_942_312), 51);
    }

    #[test]
    fn xp_for_level_no_overflow() {
        assert!(xp_for_level(89) < u64::MAX);
        assert_eq!(xp_for_level(90), u64::MAX);
        assert_eq!(xp_for_level(200), u64::MAX);
        assert_eq!(xp_for_level(u32::MAX), u64::MAX);
    }

    /// Recomputes the table from scripts/level_curve.py's formula so an edit
    /// to one side without the other fails here.
    #[test]
    fn level_table_matches_the_generator() {
        const K: f64 = 100.0;
        const ANCHORS: [(f64, f64); 4] = [
            (2.0, 5.0 / 60.0),
            (10.0, 22.0 / 60.0),
            (30.0, 5.5),
            (50.0, 8.0),
        ];
        let monster_xp = |l: u32| match l {
            1 => 2.0,
            2 => 5.0,
            3 => 10.0,
            _ => (l * l + 2 * l - 5) as f64,
        };
        let hours = |l: u32| {
            let l = l as f64;
            let (a, b) = ANCHORS
                .windows(2)
                .map(|w| (w[0], w[1]))
                .find(|(_, b)| l <= b.0)
                .unwrap();
            a.1 + (b.1 - a.1) * (l - a.0) / (b.0 - a.0)
        };
        let round2 = |x: f64| {
            let m = 10f64.powi((x.trunc().to_string().len() as i32 - 2).max(0));
            ((x / m).round() * m) as u64
        };
        let mut cum = 0;
        for level in 2..=50u32 {
            cum += round2(K * monster_xp(level - 1) * hours(level));
            assert_eq!(xp_for_level(level), cum, "level {level}");
        }
    }

    #[test]
    fn level_from_xp_max_does_not_panic() {
        // Should terminate without panic at extreme values
        let _ = level_from_xp(u64::MAX);
        let _ = level_from_xp(u64::MAX - 1);
    }

    #[test]
    fn party_share_solo_is_unchanged() {
        assert_eq!(party_xp_share(17, 1), 17);
        assert_eq!(party_xp_share(17, 0), 17);
    }

    #[test]
    fn party_share_three_members_orc() {
        // 17 * 1.50 = 25 -> 8 each, remainder dropped.
        assert_eq!(party_xp_share(17, 3), 8);
    }

    #[test]
    fn party_share_full_party_boss() {
        // 107 * 2.00 = 214 -> 42 each.
        assert_eq!(party_xp_share(107, 5), 42);
    }

    #[test]
    fn party_share_tiny_monster_pays_everyone_one() {
        // kobold (2 XP): the floored split would be 0; everyone gets 1.
        assert_eq!(party_xp_share(2, 3), 1);
        assert_eq!(party_xp_share(2, 5), 1);
        assert_eq!(party_xp_share(1, 5), 1);
        assert_eq!(party_xp_share(0, 5), 0);
    }

    #[test]
    fn party_share_never_beats_soloing() {
        // Regression for the remainder exploit: with two or more members no
        // share — the killer's included — may exceed the solo award.
        for base in [1u32, 2, 5, 10, 17, 28, 107, 401] {
            for n in 2u32..=5 {
                assert!(
                    party_xp_share(base, n) <= base,
                    "share for base {base} n {n} exceeds solo"
                );
            }
        }
    }

    #[test]
    fn death_penalty_without_level_down() {
        // Level 2 band = 59, penalty = 8.
        let result = apply_death_penalty(30);
        assert_eq!(result.old_level, 2);
        assert_eq!(result.new_level, 2);
        assert_eq!(result.xp_penalty, 8);
        assert_eq!(result.new_xp, 22);
        assert!(!result.leveled_down);
    }

    #[test]
    fn death_penalty_with_single_level_down_and_recovery_floor() {
        // Old XP 17 (Lv2 start). Penalty 8 => 9, level-down to Lv1.
        // Lv1 band = 17, recovery floor = 5. max(9, 5) = 9.
        let result = apply_death_penalty(17);
        assert_eq!(result.old_level, 2);
        assert_eq!(result.new_level, 1);
        assert_eq!(result.new_xp, 9);
        assert!(result.leveled_down);
    }

    #[test]
    fn death_penalty_never_levels_down_from_level_one() {
        let result = apply_death_penalty(1);
        assert_eq!(result.old_level, 1);
        assert_eq!(result.new_level, 1);
        assert_eq!(result.new_xp, 0);
        assert!(!result.leveled_down);
    }
}
